# Generated by Django 4.2.5 on 2023-10-14 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('change', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='..\\static\\assets\\img\\default_user.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
