# Generated by Django 4.2.5 on 2023-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0002_stockedit_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockedit',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
