# Generated by Django 4.2.4 on 2023-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
