# Generated by Django 4.2.4 on 2023-08-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0005_category_subcategory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='products'),
        ),
    ]
