# Generated by Django 4.2.1 on 2023-09-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0008_orderitem_product_id_orderitem_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='ba',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
