# Generated by Django 4.2.4 on 2023-09-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0011_remove_user_ba_user_personal_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ba',
        ),
        migrations.AddField(
            model_name='order',
            name='personal_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
