# Generated by Django 4.2.4 on 2023-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0012_remove_order_ba_order_personal_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
